using Blef.Modules.Games.Api.Tests.Core;
using Blef.Modules.Games.Api.Tests.Scenarios.ValueObjects;

namespace Blef.Modules.Games.Api.Tests.Scenarios.HappyPath;

[UsesVerify]
public class FourPlayersPlayTheGame
{
    [Fact]
    public async Task Scenario()
    {
        var results = await new TestBuilder()
            .NewGame()
            .GetGameFlow()
            .JoinPlayer(WhichPlayer.Knuth)
            .JoinPlayer(WhichPlayer.Graham)
            .JoinPlayer(WhichPlayer.Conway)
            .JoinPlayer(WhichPlayer.Riemann)
            .NewDeal()
            .GetGameFlow()
            .GetDealFlow(new DealNumber(1))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(1), description: "Knuth has one card")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(1), description: "Graham has one card")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(1), description: "Conway has one card")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(1), description: "Riemann has one card")
            .BidHighCard(WhichPlayer.Knuth, FaceCard.Nine, description: "Knuth starts the deal")
            .BidHighCard(WhichPlayer.Graham, FaceCard.Ten)
            .BidHighCard(WhichPlayer.Conway, FaceCard.Jack)
            .BidHighCard(WhichPlayer.Riemann, FaceCard.Queen)
            .Check(WhichPlayer.Knuth, description: "Knuth checks the bid, Riemann get lost the deal")
            .GetGameFlow()
            .GetDealFlow(deal: new DealNumber(1))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(2), description: "Knuth has one card")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(2), description: "Graham has one card")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(2), description: "Conway has one card")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(2), description: "Riemann has two card")
            .BidPair(WhichPlayer.Graham, FaceCard.Ace, description: "Bad move Graham! Knuth should start the deal")
            .Check(WhichPlayer.Conway, description: "Bad move Conway! Knuth should start the deal")
            .BidPair(WhichPlayer.Knuth, FaceCard.Ace, description: "Knuth starts the deal")
            .Check(WhichPlayer.Graham, description: "Graham checks the bid and get lost the deal")
            .GetGameFlow()
            .GetDealFlow(deal: new DealNumber(2))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(3), description: "Knuth has one card")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(3), description: "Graham has two cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(3), description: "Conway has one card")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(3), description: "Riemann has two cards")
            .BidPair(WhichPlayer.Conway, FaceCard.King, description: "Conway starts the deal")
            .BidThreeOfAKind(WhichPlayer.Knuth, FaceCard.Ace, description: "Bad move Knuth! Riemann has move now")
            .BidThreeOfAKind(WhichPlayer.Riemann, FaceCard.Ace)
            .Check(WhichPlayer.Knuth, description: "Knuth checks the bid, Riemann get lost the deal")
            .GetGameFlow()
            .GetDealFlow(deal: new DealNumber(3))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(4), description: "Knuth has one card")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(4), description: "Graham has two cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(4), description: "Conway has one card")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(4), description: "Riemann has three cards")
            .BidFourOfAKind(WhichPlayer.Knuth, FaceCard.Nine)
            .BidStraightFlush(WhichPlayer.Riemann, Suit.Clubs, description: "Bad move Riemann! Graham has move now")
            .Check(WhichPlayer.Conway, description: "Bad move Conway! Graham has move now")
            .BidHighStraight(WhichPlayer.Knuth, description: "Bad move Knuth!, Graham has move now")
            .Check(WhichPlayer.Graham, description: "Graham checks the bid, Knuth get lost the deal")
            .Check(WhichPlayer.Knuth, description: "Bad move Knuth! the deal has been ended")
            .GetGameFlow()
            .GetDealFlow(deal: new DealNumber(4))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(5), description: "Knuth has two cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(5), description: "Graham has two cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(5), description: "Conway has one card")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(5), description: "Riemann has three cards")
            .BidStraightFlush(WhichPlayer.Knuth, Suit.Clubs,
                description: "Bad move Knuth! Graham should start the deal")
            .Check(WhichPlayer.Graham, description: "Bad move Graham! There is no bid to check in this deal")
            .BidHighCard(WhichPlayer.Graham, FaceCard.Ace, description: "Graham starts the deal")
            .Check(WhichPlayer.Conway, description: "Conway checks the bid and get lost the deal")
            .GetGameFlow()
            .GetDealFlow(deal: new DealNumber(5))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(6), description: "Knuth has two cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(6), description: "Graham has two cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(6), description: "Conway has two cards")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(6), description: "Riemann has three cards")
            .BidHighStraight(WhichPlayer.Riemann, description: "Riemann starts the deal")
            .Check(WhichPlayer.Knuth, description: "Knuth checks the bid and get lost the deal")
            .GetGameFlow()
            .GetDealFlow(deal: new DealNumber(6))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(7), description: "Knuth has three cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(7), description: "Graham has two cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(7), description: "Conway has two cards")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(7), description: "Riemann has three cards")
            .BidFullHouse(WhichPlayer.Graham, FaceCard.Ace, FaceCard.King, description: "Graham starts the deal")
            .Check(WhichPlayer.Conway, description: "Conway checks the bid and get lost the deal")
            .GetGameFlow()
            .GetDealFlow(deal: new DealNumber(7))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(8), description: "Knuth has three cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(8), description: "Graham has two cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(8), description: "Conway has three cards")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(8), description: "Riemann has three cards")
            .BidTwoPairs(WhichPlayer.Riemann, FaceCard.Ace, FaceCard.King, description: "Riemann starts the deal")
            .BidTwoPairs(WhichPlayer.Knuth, FaceCard.King, FaceCard.Ace,
                description: "Bad move Knuth!, next bid should be higher")
            .BidThreeOfAKind(WhichPlayer.Knuth, FaceCard.King)
            .BidThreeOfAKind(WhichPlayer.Graham, FaceCard.Ace)
            .BidFourOfAKind(WhichPlayer.Conway, FaceCard.King)
            .BidFourOfAKind(WhichPlayer.Riemann, FaceCard.Ace)
            .Check(WhichPlayer.Knuth, description: "Knuth checks the bid, Riemann get lost the deal")
            .GetGameFlow()
            .GetDealFlow(deal: new DealNumber(8))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(9), description: "Knuth has three cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(9), description: "Graham has two cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(9), description: "Conway has three cards")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(9), description: "Riemann has four cards")
            .BidTwoPairs(WhichPlayer.Knuth, FaceCard.Ace, FaceCard.King, description: "Knuth starts the deal")
            .BidTwoPairs(WhichPlayer.Graham, FaceCard.Ace, FaceCard.King, description: "Bad move Graham!")
            .BidTwoPairs(WhichPlayer.Conway, FaceCard.Ace, FaceCard.King, description: "Bad move Conway!")
            .Check(WhichPlayer.Knuth, description: "Bad move Knuth!")
            .Check(WhichPlayer.Graham, description: "Graham checks the bid and lost the deal")
            .GetGameFlow()
            .GetDealFlow(new DealNumber(9))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(10), description: "Knuth has three cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(10), description: "Graham has three cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(10), description: "Conway has three cards")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(10), description: "Riemann has four cards")
            .BidHighCard(WhichPlayer.Conway, FaceCard.Ace, description: "Conway starts the deal")
            .Check(WhichPlayer.Riemann, description: "Riemann checks the bid and lost the deal")
            .GetGameFlow()
            .GetDealFlow(new DealNumber(10))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(11), description: "Knuth has three cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(11), description: "Graham has three cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(11), description: "Conway has three cards")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(11), description: "Riemann has five cards")
            .BidFlush(WhichPlayer.Knuth, Suit.Clubs, description: "Conway starts the deal")
            .Check(WhichPlayer.Graham, description: "Graham checks the bid and get lost the deal")
            .GetGameFlow()
            .GetDealFlow(new DealNumber(11))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(12), description: "Knuth has three cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(12), description: "Graham has four cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(12), description: "Conway has three cards")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(12), description: "Riemann has five cards")
            .BidHighStraight(WhichPlayer.Conway, description: "Conway starts the deal")
            .Check(WhichPlayer.Riemann, description: "Riemann checks the bid and get lost the GAME!")
            .GetGameFlow()
            .GetDealFlow(new DealNumber(12))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(13), description: "Knuth has three cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(13), description: "Graham has four cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(13), description: "Conway has three cards")
            .GetCards(WhichPlayer.Riemann, deal: new DealNumber(13), description: "Riemann lost the game")
            .BidHighCard(WhichPlayer.Knuth, FaceCard.Ace, description: "Knuth starts the deal")
            .Check(WhichPlayer.Graham, description: "Graham checks the bid and lost the deal")
            .GetGameFlow()
            .GetDealFlow(new DealNumber(13))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(14), description: "Knuth has three cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(14), description: "Graham has five cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(14), description: "Conway has three cards")
            .BidPair(WhichPlayer.Conway, FaceCard.Ace, description: "Conway starts the deal")
            .BidFourOfAKind(WhichPlayer.Knuth, FaceCard.Ace)
            .Check(WhichPlayer.Graham, description: "Graham checks the bid, Knuth get lost the deal")
            .GetGameFlow()
            .GetDealFlow(new DealNumber(14))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(15), description: "Knuth has four cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(15), description: "Graham has five cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(15), description: "Conway has three cards")
            .BidHighCard(WhichPlayer.Graham, FaceCard.Ace, description: "Graham starts the deal")
            .Check(WhichPlayer.Conway, description: "Conway checks the bid and lost the deal")
            .GetGameFlow()
            .GetDealFlow(new DealNumber(15))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(16), description: "Knuth has four cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(16), description: "Graham has five cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(16), description: "Conway has four cards")
            .BidHighCard(WhichPlayer.Knuth, FaceCard.Ace, description: "Knuth starts the deal")
            .Check(WhichPlayer.Graham, description: "Graham checks the bid and get lost the GAME!")
            .GetGameFlow()
            .GetDealFlow(new DealNumber(16))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(17), description: "Knuth has four cards")
            .GetCards(WhichPlayer.Graham, deal: new DealNumber(17), description: "Graham lost the game")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(17), description: "Conway has four cards")
            .BidHighCard(WhichPlayer.Conway, FaceCard.Ace, description: "Conway starts the deal")
            .Check(WhichPlayer.Knuth, description: "Knuth checks the bid and get lost the deal")
            .GetGameFlow()
            .GetDealFlow(new DealNumber(17))
            .GetCards(WhichPlayer.Knuth, deal: new DealNumber(18), description: "Knuth has five cards")
            .GetCards(WhichPlayer.Conway, deal: new DealNumber(18), description: "Conway has four cards")
            .BidHighCard(WhichPlayer.Conway, FaceCard.Ace, description: "Conway starts the deal")
            .Check(WhichPlayer.Knuth, description: "Knuth checks the bid and get lost the GAME!")
            .GetGameFlow(description: "THE WINNER IS CONWAY!")
            .GetDealFlow(new DealNumber(18))
            .Build();

        await Verify(results);
    }
}