# Face cards
# - nine
# - ten
# - jack
# - queen
# - king
# - ace

# Suit
# - clubs
# - diamonds
# - hearts
# - spades

@module = games-module
@api = {{host}}/{{module}}

### Make a game
@gameId = {{make_game.response.body.gameId}}
# @name make_game
POST {{api}}/games
Content-Type: application/json

### Get gameplay
GET {{api}}/gameplays/{{gameId}}
Content-Type: application/json

### Player 1: Join game
@playerKnuthNick = Knuth
@playerKnuthId = {{player_knuth_join_game.response.body.playerId}}
# @name player_knuth_join_game
POST {{api}}/games/{{gameId}}/players
Content-Type: application/json

{
    "nick": "{{playerKnuthNick}}"
}

### Player 2: Join game
@playerGrahamNick = Graham
@playerGrahamId = {{player_graham_join_game.response.body.playerId}}
# @name player_graham_join_game
POST {{api}}/games/{{gameId}}/players
Content-Type: application/json

{
    "nick": "{{playerGrahamNick}}"
}

### Player 3: Join game
@playerRiemannNick = Riemann
@playerRiemannId = {{player_riemann_join_game.response.body.playerId}}
# @name player_riemann_join_game
POST {{api}}/games/{{gameId}}/players
Content-Type: application/json

{
    "nick": "{{playerRiemannNick}}"
}

###
@dealNumber = 1

### Get deal
GET {{api}}/gameplays/{{gameId}}/deals/{{dealNumber}}
Content-Type: application/json

### First deal (shuffling and dealing)
POST {{api}}/games/{{gameId}}/deals
Content-Type: application/json

### Player 1: Get player's cards
GET {{api}}/games/{{gameId}}/players/{{playerKnuthId}}/deals/{{dealNumber}}/cards
Content-Type: application/json

### Player 2: Get player's cards
GET {{api}}/games/{{gameId}}/players/{{playerGrahamId}}/deals/{{dealNumber}}/cards
Content-Type: application/json

### Player 3: Get player's cards
GET {{api}}/games/{{gameId}}/players/{{playerRiemannId}}/deals/{{dealNumber}}/cards
Content-Type: application/json

### Player 1: Bid
POST {{api}}/games/{{gameId}}/players/{{playerKnuthId}}/bids
Content-Type: application/json

{
    "pokerHand": "high-card:nine"
}

### Player 1: Bid: High Card
POST {{api}}/games/{{gameId}}/players/{{playerKnuthId}}/bids/high-card
Content-Type: application/json

{
    "faceCard": "nine"
}

### Player 2: Bid
POST {{api}}/games/{{gameId}}/players/{{playerGrahamId}}/bids
Content-Type: application/json

{
    "pokerHand": "high-card:ten"
}

### Player 3: Bid
POST {{api}}/games/{{gameId}}/players/{{playerRiemannId}}/bids
Content-Type: application/json

{
    "pokerHand": "high-card:jack"
}

### Player 1: Check
POST {{api}}/games/{{gameId}}/players/{{playerKnuthId}}/checks
Content-Type: application/json

### Player 2: Check
POST {{api}}/games/{{gameId}}/players/{{playerGrahamId}}/checks
Content-Type: application/json

### Player 3: Check
POST {{api}}/games/{{gameId}}/players/{{playerRiemannId}}/checks
Content-Type: application/json