# Face cards translation
# - 1 means 'nine'
# - 2 means 'ten'
# - 3 means 'jack'
# - 4 means 'queen'
# - 5 means 'king'
# - 6 means 'ace'

# Suits translation
# - 1 means 'clubs'
# - 2 means 'diamonds'
# - 3 means 'hearts'
# - 4 means 'spades'

# Bid poker hand options
# - high-card:nine
# - high-card:ten
# - high-card:jack
# - high-card:queen
# - high-card:king
# - high-card:ace

@module = games-module
@api = {{host}}/{{module}}

### Make a game
@gameId = {{make_game.response.body.gameId}}
# @name make_game
POST {{api}}/games
Content-Type: application/json

### Get game flow
GET {{api}}/games/{{gameId}}
Content-Type: application/json

### Player 1: Join game
@playerKnuthNick = Knuth
@playerKnuthId = {{player_knuth_join_game.response.body.playerId}}
# @name player_knuth_join_game
POST {{api}}/games/{{gameId}}/players
Content-Type: application/json

{
    "nick": "{{playerKnuthNick}}"
}

### Player 2: Join game
@playerGrahamNick = Graham
@playerGrahamId = {{player_graham_join_game.response.body.playerId}}
# @name player_graham_join_game
POST {{api}}/games/{{gameId}}/players
Content-Type: application/json

{
    "nick": "{{playerGrahamNick}}"
}

### Player 3: Join game
@playerRiemannNick = Riemann
@playerRiemannId = {{player_riemann_join_game.response.body.playerId}}
# @name player_riemann_join_game
POST {{api}}/games/{{gameId}}/players
Content-Type: application/json

{
    "nick": "{{playerRiemannNick}}"
}

### Player 1: Get player's cards
GET {{api}}/games/{{gameId}}/players/{{playerKnuthId}}/cards
Content-Type: application/json

### Player 2: Get player's cards
GET {{api}}/games/{{gameId}}/players/{{playerGrahamId}}/cards
Content-Type: application/json

### Player 3: Get player's cards
GET {{api}}/games/{{gameId}}/players/{{playerRiemannId}}/cards
Content-Type: application/json

### Player 1: Bid
POST {{api}}/games/{{gameId}}/players/{{playerKnuthId}}/bids
Content-Type: application/json

{
    "pokerHand": "high-card:nine"
}

### Player 2: Bid
POST {{api}}/games/{{gameId}}/players/{{playerGrahamId}}/bids
Content-Type: application/json

{
    "pokerHand": "high-card:ten"
}

### Player 3: Bid
POST {{api}}/games/{{gameId}}/players/{{playerRiemannId}}/bids
Content-Type: application/json

{
    "pokerHand": "high-card:jack"
}

### Player 1: Check
POST {{api}}/games/{{gameId}}/players/{{playerKnuthId}}/checks
Content-Type: application/json

### Player 2: Check
POST {{api}}/games/{{gameId}}/players/{{playerGrahamId}}/checks
Content-Type: application/json

### Player 3: Check
POST {{api}}/games/{{gameId}}/players/{{playerRiemannId}}/checks
Content-Type: application/json