@module = games-module
@api = {{host}}/{{module}}

### Make a tournament
@tournamentId = {{make_tournament.response.body.tournamentId}}
# @name make_tournament
POST {{api}}/tournaments
Content-Type: application/json

### Player 1: Join turnament
@playerOneId = {{player_one_join_game.response.body.playerId}}
# @name player_one_join_game
POST {{api}}/tournaments/{{tournamentId}}/players
Content-Type: application/json

{
    "nick": "Player One"
}

### Player 2: Join turnament
@playerTwoId = {{player_two_join_game.response.body.playerId}}
# @name player_two_join_game
POST {{api}}/tournaments/{{tournamentId}}/players
Content-Type: application/json

{
    "nick": "Player Two"
}

### Start tournament
# @name start_tournament
POST {{api}}/tournaments/{{tournamentId}}/start
Content-Type: application/json

### Get current game in tournament
@gameId = {{get_current_game.response.body.gameId}}
# @name get_current_game
GET {{api}}/tournaments/{{tournamentId}}/games/current
Content-Type: application/json

### Player 1: Get player's cards
GET {{api}}/games/{{gameId}}/players/{{playerOneId}}/cards
Content-Type: application/json

### Player 2: Get player's cards
GET {{api}}/games/{{gameId}}/players/{{playerTwoId}}/cards
Content-Type: application/json

### Player 1: Bid
POST {{api}}/games/{{gameId}}/players/{{playerOneId}}/bids
Content-Type: application/json

{
    "pokerHand": "high-card:nine"
}

### Player 2: Bid
POST {{api}}/games/{{gameId}}/players/{{playerTwoId}}/bids
Content-Type: application/json

{
    "pokerHand": "high-card:ten"
}

### Player 1: Check
POST {{api}}/games/{{gameId}}/players/{{playerOneId}}/checks
Content-Type: application/json

### Player 2: Check
POST {{api}}/games/{{gameId}}/players/{{playerTwoId}}/checks
Content-Type: application/json

### Get game flow
GET {{api}}/games/{{gameId}}
Content-Type: application/json