@module = games-module
@api = {{host}}/{{module}}

### Make a game
@gameId = {{make_game.response.body.gameId}}
# @name make_game
POST {{api}}/games
Content-Type: application/json

### Player 1: Join game
@playerOne = {{player_one_join_game.response.headers.Location}}
# @name player_one_join_game
POST {{api}}/games/{{gameId}}/players
Content-Type: application/json

{
    "playerId": "{{$guid}}"
}

### Player 2: Join game
@playerTwo = {{player_two_join_game.response.headers.Location}}
# @name player_two_join_game
POST {{api}}/games/{{gameId}}/players
Content-Type: application/json

{
    "playerId": "{{$guid}}"
}

# Face cards translation
# - 1 means 'nine'
# - 2 means 'ten'
# - 3 means 'jack'
# - 4 means 'queen'
# - 5 means 'king'
# - 6 means 'ace'

# Suits translation
# - 1 means 'clubs'
# - 2 means 'diamonds'
# - 3 means 'hearts'
# - 4 means 'spades'

### Player 1: Get player cards
GET {{host}}/{{playerOne}}/cards
Content-Type: application/json

### Player 2: Get player cards
GET {{host}}/{{playerTwo}}/cards
Content-Type: application/json

# Bid poker hand options
# - one-of-a-kind:nine
# - one-of-a-kind:ten
# - one-of-a-kind:jack
# - one-of-a-kind:queen
# - one-of-a-kind:king
# - one-of-a-kind:ace

### Player 1: Bid
POST {{host}}/{{playerOne}}/bids
Content-Type: application/json

{
    "pokerHand": "one-of-a-kind:nine"
}

### Player 2: Bid
POST {{host}}/{{playerTwo}}/bids
Content-Type: application/json

{
    "pokerHand": "one-of-a-kind:ten"
}

### Player 1: Check
POST {{host}}/{{playerOne}}/checks
Content-Type: application/json

### Player 2: Check
POST {{host}}/{{playerTwo}}/checks
Content-Type: application/json

### Get looser
GET {{api}}/games/{{gameId}}/looser
Content-Type: application/json