# Face cards translation
# - 1 means 'nine'
# - 2 means 'ten'
# - 3 means 'jack'
# - 4 means 'queen'
# - 5 means 'king'
# - 6 means 'ace'

# Suits translation
# - 1 means 'clubs'
# - 2 means 'diamonds'
# - 3 means 'hearts'
# - 4 means 'spades'

# Bid poker hand options
# - one-of-a-kind:nine
# - one-of-a-kind:ten
# - one-of-a-kind:jack
# - one-of-a-kind:queen
# - one-of-a-kind:king
# - one-of-a-kind:ace

@module = games-module
@api = {{host}}/{{module}}

### Make a game
@gameId = {{make_game.response.body.gameId}}
# @name make_game
POST {{api}}/games
Content-Type: application/json

### Get game flow
GET {{api}}/games/{{gameId}}
Content-Type: application/json

### Player 1: Join game
@playerOneId = {{player_one_join_game.response.body.playerId}}
# @name player_one_join_game
POST {{api}}/games/{{gameId}}/players
Content-Type: application/json

{
    "nick": "Player One"
}

### Player 2: Join game
@playerTwoId = {{player_two_join_game.response.body.playerId}}
# @name player_two_join_game
POST {{api}}/games/{{gameId}}/players
Content-Type: application/json

{
    "nick": "Player Two"
}

### Player 1: Get player's cards
GET {{api}}/games/{{gameId}}/players/{{playerOneId}}/cards
Content-Type: application/json

### Player 2: Get player's cards
GET {{api}}/games/{{gameId}}/players/{{playerTwoId}}/cards
Content-Type: application/json

### Player 1: Bid
POST {{api}}/games/{{gameId}}/players/{{playerOneId}}/bids
Content-Type: application/json

{
    "pokerHand": "one-of-a-kind:nine"
}

### Player 2: Bid
POST {{api}}/games/{{gameId}}/players/{{playerTwoId}}/bids
Content-Type: application/json

{
    "pokerHand": "one-of-a-kind:ten"
}

### Player 1: Check
POST {{api}}/games/{{gameId}}/players/{{playerOneId}}/checks
Content-Type: application/json

### Player 2: Check
POST {{api}}/games/{{gameId}}/players/{{playerTwoId}}/checks
Content-Type: application/json