@host = https://localhost:49153 
@module = games-module
@api = {{host}}/{{module}}

### Make a tournament
@tournamentId = {{make_tournament.response.body.tournamentId}}
# @name make_tournament
POST {{api}}/tournaments
Content-Type: application/json

### Join tournament
@playerLocation = {{join_tournament.response.headers.Location}}
# @name join_tournament
POST {{api}}/tournaments/{{tournamentId}}/players
Content-Type: application/json

{
    "playerId": "3adabc6d-d573-4b23-98bc-1c62d5bb5543"
}

### Start tournament
# @name start_tournament
POST {{api}}/tournaments/{{tournamentId}}/start
Content-Type: application/json

### Get current game in tournament
@gameId = {{get_current_game.response.body.gameId}}
# @name get_current_game
GET {{api}}/tournaments/{{tournamentId}}/games/current
Content-Type: application/json

### Get player cards
GET {{host}}/games-module/games/{{gameId}}/players/3adabc6d-d573-4b23-98bc-1c62d5bb5543/cards
Content-Type: application/json

### Bid Jack
POST {{host}}/games-module/games/{{gameId}}/players/3adabc6d-d573-4b23-98bc-1c62d5bb5543/bids
Content-Type: application/json

{
    "pokerHand": "one-of-a-kind:Jack"
}

### Check
POST {{host}}/games-module/games/{{gameId}}/players/3adabc6d-d573-4b23-98bc-1c62d5bb5543/checks
Content-Type: application/json
