name: Build and publish Docker image to Docker Hub and deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-and-publish:
    name: Build and publish Docker image to DockerHub repository
    environment: production
    runs-on: ubuntu-latest
    
    outputs:
      image-digest: ${{ steps.setup-digest.outputs.digest_value }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push to Docker Hub and GitHub Container Registry
      id: build-and-publish
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
            teovincent/blef:latest 
            ghcr.io/arturwincenciak/blef:latest
        push: ${{ github.ref == 'refs/heads/main' }}
        
    - name: Echo image digest
      run: echo 'Digest ${{ steps.build-and-publish.outputs.digest }}'
      
    - name: Setup job output image digest value
      id: setup_digest
      run: echo "::set-output name=digest-value::${{ steps.build-and-publish.outputs.digest }}"

  deploy_image:
    name: Deploy Docker image to Azure
    runs-on: ubuntu-latest
    needs: build-and-publish
    environment:
      name: 'production'

    steps:
    - name: Echo image digest
      run: echo 'Digest ${{ needs.build-and-publish.outputs.imagedigest }}'
      
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'blef'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8f7b17ddf5a24d228eebe55cecad2b91 }}
        images: 'index.docker.io/teovincent/blef:latest@${{ needs.build-and-publish.outputs.image-digest }}'
