name: v2.0 Deploy DockerHub, Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build_and_publish:
    name: Publish Docker Image
    environment: production
    runs-on: ubuntu-latest

    outputs:
      imagedigest: ${{ steps.setup_digest.outputs.digest_value }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to Github Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push to Docker Hub and GitHub Container Registry
      id: build_and_publish
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: |
            teovincent/blef:latest
            ghcr.io/arturwincenciak/blef:latest
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Echo image digest
      run: echo 'Digest ${{ steps.build_and_publish.outputs.digest }}'

    - name: Setup job output image digest value
      id: setup_digest
      run: echo "::set-output name=digest_value::${{ steps.build_and_publish.outputs.digest }}"

  deploy_image:
    name: Deploy to Azure
    environment: production
    runs-on: ubuntu-latest
    needs: build_and_publish

    steps:
    - name: Echo image digest
      run: echo 'Digest ${{ needs.build_and_publish.outputs.imagedigest }}'

    - name: Deploy Docker image to Azure
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'blef'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8f7b17ddf5a24d228eebe55cecad2b91 }}
        images: 'index.docker.io/teovincent/blef:latest@${{ needs.build_and_publish.outputs.imagedigest }}'