name: Build and publish Docker image to Docker Hub and deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    name: Build and publish Docker image to DockerHub repository
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
            teovincent/blef:latest 
            ghcr.io/arturwincenciak/blef:latest
        push: ${{ github.ref == 'refs/heads/main' }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'blef'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8f7b17ddf5a24d228eebe55cecad2b91 }}
        images: 'index.docker.io/teovincent/blef:latest@sha256:62dfcb2d23b53a487ced690ed931c083a5b7b0a73290b281236c3a80e751f05b'
