name: Build and publish Docker image to Docker Hub and deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    name: CD Build and test
    environment:
      name: 'integration'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore Blef.sln

    - name: Build
      run: dotnet build Blef.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test Blef.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

  build_and_publish:
    name: Build and publish image to DockerHub repository
    environment: production
    runs-on: ubuntu-latest
    needs: build_and_test
    
    outputs:
      imagedigest: ${{ steps.setup_digest.outputs.digest_value }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push to Docker Hub and GitHub Container Registry
      id: build_and_publish
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
            teovincent/blef:latest 
            ghcr.io/arturwincenciak/blef:latest
        push: ${{ github.ref == 'refs/heads/main' }}
        
    - name: Echo image digest
      run: echo 'Digest ${{ steps.build_and_publish.outputs.digest }}'
      
    - name: Setup job output image digest value
      id: setup_digest
      run: echo "::set-output name=digest_value::${{ steps.build_and_publish.outputs.digest }}"

  deploy_image:
    name: Deploy image to Azure job
    runs-on: ubuntu-latest
    needs: build_and_publish
    environment:
      name: 'production'

    steps:
    - name: Echo image digest
      run: echo 'Digest ${{ needs.build_and_publish.outputs.imagedigest }}'
      
    - name: Deploy image to Azure step
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'blef'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8f7b17ddf5a24d228eebe55cecad2b91 }}
        images: 'index.docker.io/teovincent/blef:latest@${{ needs.build_and_publish.outputs.imagedigest }}'
