name: v2.0 CleanUp Code

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  r-sharp-cleanup:
    name: R# Cleanup Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore Blef.sln

      - name: Cleanup Code
        id: cleanup
        uses: ArturWincenciak/ReSharper_CleanupCode@38e6009d6133e855a08f30f3d7d64ba5f317648b
        with:
          solution: 'Blef.sln'
          fail_on_reformat_needed: 'yes'
          auto_commit: 'no'
          jb_cleanup_code_arg: '--verbosity=WARN --profile=Blef: Full Cleanup --exclude=**UnitTests/**.*'