name: Cleanup and Inspect Code

on: [push]

jobs:
  cleanup_job:
    runs-on: ubuntu-latest
    name: CLI CleanupCode

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore Blef.sln

    - name: Cleanup code
      id: clean_code
      run: sh ./scripts/cleanup-code/github-action-cleanupcode.sh -f no -a yes

  inspection_job:
    runs-on: ubuntu-latest
    name: CLI InspectCode
    needs: cleanup_job

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore Blef.sln

    - name: Inspect code
      uses: muno92/resharper_inspectcode@1.6.6
      with:
        solutionPath: ./Blef.sln
        failOnIssue: 1
        minimumSeverity: notice
        solutionWideAnalysis: true
